apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  argocd.argoproj.io/sync-wave: "0"
  name: platform
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/iahmedsabry/k8s-gitops.git
    targetRevision: main
    path: apps/infrastructure

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m