apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default

  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 5.51.6
    helm:
      valueFiles:
        - values.yaml
      # parameters |
      #   configs:
      #     params:
      #       server.insecure: true
          
      #     secret:
      #       argocdServerSecretKey: "T/QlZtmWcp1E9Hjvsc26bd85dY8YpkLAt4a5+yFld8o="

      #   server:
      #     service:
      #       type: NodePort

      #     extraArgs:
      #       - --insecure

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true