apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  server.secretkey: "3plLV8AnbxoXzqlSvapoBvjzU+6TffAXhUWwQJnDZog="