apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
      <body>
        <h1>Hello World!</h1>
        <p>This is deployed via ArgoCD</p>
      </body>
    </html>