apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-routing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iahmedsabry/k8s-gitops
    targetRevision: main
    path: manifests/aws-routing
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true